image:
  name: bearsan/haproxy-ccm
  tag: 0.1.0
  useImagePullSecret:
    enabled: false
    name: ""
env:
  useExistsSecret:
    enabled: false
    secretRef:
      baseUrl:
        name: ""
        key: ""
      auth:
        name: ""
        key: ""
  baseUrl: ""
  auth: ""
