image:
  name: bearsan/haproxy-ccm
  tag: 0.1.0
  useImagePullSecret:
    enabled: false
    name: ""
env:
  useExistsSecret:
    enabled: false
    secretRef:
      baseUrl:
        name: ""
        key: ""
      auth:
        name: ""
        key: ""
  baseUrl: ""
  auth: ""

# Additional command line arguments for haproxy-ccm
args:
  # Cloud provider specific arguments
  cloudProvider: "haproxy"
  
  # Additional custom arguments (list format)
  # Example:
  # - "--log-level=debug"
  # - "--bind-address=0.0.0.0"
  # - "--port=10258"
  additional: []
